// Cloudflare Pages Function - Data Lake Proxy (Stocks)
// Version: GITHUB-DATA-LAKE-CF-V1 (Forced Update 2026-01-18)
// Sourcing from Static GitHub Assets to prevent 429 blocking

const STATIC_DATA_URL = 'https://raw.githubusercontent.com/Bhidy/Mubasher-Stock-Game/main/public/data/stocks.json';

export async function onRequest(context) {
    const { request } = context;
    const url = new URL(request.url);
    const market = url.searchParams.get('market') || 'Global'; // Default to Global/US if missing

    try {
        // Fetch the PRE-COMPUTED JSON file from GitHub Raw
        // This file is generated by GitHub Actions every 10 minutes
        const response = await fetch(STATIC_DATA_URL, {
            headers: {
                'User-Agent': 'StockHero-CF-Proxy/1.0',
                // Add Cache-Control to ensure we don't get super stale Github data if they cache internally
                'Cache-Control': 'no-cache'
            },
            cf: {
                // Cloudflare specific caching instructions for the fetch
                cacheTtl: 60,
                cacheEverything: true
            }
        });

        if (!response.ok) {
            throw new Error(`Data Lake unreachable: ${response.status}`);
        }

        const rawData = await response.json();

        // Extract specific market data
        // The JSON structure is { "SA": [...], "US": [...] }
        const marketData = rawData[market] || [];

        return new Response(JSON.stringify(marketData), {
            status: 200,
            headers: {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*',
                'Cache-Control': 'public, max-age=60, stale-while-revalidate=300', // Cache for 1 min
                'X-Data-Source': 'GitHub-Data-Lake-CF'
            }
        });

    } catch (error) {
        console.error('[Stocks-CF] Error:', error.message);
        return new Response(JSON.stringify({
            error: 'Failed to retrieve market data',
            details: error.message,
            source: 'Static Data Lake'
        }), {
            status: 500,
            headers: {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*'
            }
        });
    }
}
