// Cloudflare/Vercel Proxy for Stocks
// Version: GITHUB-DATA-LAKE-PROD-V1
// Sourcing from Static GitHub Assets to prevent 429 blocking

const STATIC_DATA_URL = 'https://raw.githubusercontent.com/Bhidy/Mubasher-Stock-Game/main/public/data/stocks.json';
const FALLBACK_DATA_URL = 'https://bhidy.github.io/Mubasher-Stock-Game/data/stocks.json';

// VERCEL SERVERLESS HANDLER
export default async function handler(req, res) {
    const market = req.query.market || 'SA';
    const startTime = Date.now();

    try {
        console.log(`📡 Fetching stock data for ${market} from Data Lake...`);

        // Fetch the PRE-COMPUTED JSON file
        // This file is generated by GitHub Actions every 10 minutes
        // It contains ALL markets. We fetch once, then filter.
        let rawData = null;

        try {
            const response = await fetch(STATIC_DATA_URL, {
                headers: { 'User-Agent': 'StockHero-Vercel-Proxy/1.0' },
                next: { revalidate: 60 } // Vercel cache hint
            });
            if (!response.ok) throw new Error(`HTTP ${response.status}`);
            rawData = await response.json();
            console.log('✅ Fetched from RAW GitHub Content');
        } catch (e) {
            console.warn('⚠️ Raw fetch failed, trying Pages Fallback:', e.message);
            // Fallback to GitHub Pages CDN
            const response = await fetch(FALLBACK_DATA_URL);
            if (!response.ok) throw new Error(`Fallback HTTP ${response.status}`);
            rawData = await response.json();
        }

        if (!rawData) {
            throw new Error('No data received from Data Lake');
        }

        // Extract specific market data
        // The JSON structure is { "SA": [...], "US": [...] }
        const marketData = rawData[market] || [];

        // Performance Metric
        const duration = Date.now() - startTime;
        console.log(`🚀 Served ${marketData.length} stocks for ${market} in ${duration}ms`);

        // Response Headers
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Cache-Control', 's-maxage=60, stale-while-revalidate=300'); // Cache for 1 min, stale for 5
        res.setHeader('X-Data-Source', 'GitHub-Data-Lake');

        res.status(200).json(marketData);

    } catch (error) {
        console.error('❌ Data Lake Error:', error.message);

        // Final fallback: Return empty array but 200 to dont break frontend (or 500 if critical)
        res.status(500).json({
            error: 'Failed to retrieve market data',
            details: error.message,
            source: 'Static Data Lake'
        });
    }
}
